name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Grant execute permissions to the Gradle Wrapper
      - name: Grant Execute Permission for Gradlew
        run: chmod +x ./gradlew

      # Set up Gradle and enable dependency caching
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.9' # Specify the Gradle version you want
          cache-read-only: false

      # Build the project with the Gradle Wrapper
      - name: Build with Gradle Wrapper
        run: ./gradlew build --info
      
  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Generate and submit dependency graph
      - name: Generate and Submit Dependency Graph
        uses: gradle/actions/dependency-submission@v4
